// <auto-generated />
using System;
using EmployeeRecognitionPortal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System.Linq;
using System.Data;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeRecognitionPortal.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("EmployeeRecognitionPortal.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<bool?>("IsDeleted");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("EmployeeRecognitionPortal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<bool?>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<byte[]>("Signature")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EmployeeRecognitionPortal.Models.EmpOfMonth", b =>
            {


                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<DateTime>("DateAwarded")
                    .IsRequired();

                b.Property<string>("EmployeeEmail")
                    .IsRequired();

                b.Property<string>("EmployeeName")
                    .IsRequired();

                b.Property<int>("AwardCreatorId")
                    .IsRequired();

                b.Property<User>("AwardCreator");

                b.Property<string>("LaTexFile");

                b.ToTable("EmpOfMonths");

                b.HasKey("Id");

                b.HasOne("EmployeeRecognitionPortal.Models.User")
                    .WithOne()
                    .HasForeignKey("Id");
            });

            modelBuilder.Entity("EmployeeRecognitionPortal.Models.EmpOfYear", b =>
            {


                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<DateTime>("DateAwarded")
                    .IsRequired();

                b.Property<string>("EmployeeEmail")
                    .IsRequired();

                b.Property<string>("EmployeeName")
                    .IsRequired();

                b.Property<int>("AwardCreatorId")
                    .IsRequired();

                b.Property<User>("AwardCreator");

                b.Property<string>("LaTexFile");

                b.ToTable("EmpOfYears");

                b.HasKey("Id");

                b.HasOne("EmployeeRecognitionPortal.Models.User")
                    .WithOne()
                    .HasForeignKey("Id");
            });


#pragma warning restore 612, 618
        }
    }
}
